CREATE TABLE member(
	userid VARCHAR2(6) PRIMARY KEY,
	userpw VARCHAR2(6) NOT NULL,
	username VARCHAR2(18) NOT NULL,
	email VARCHAR2(100),
	regdate DATE DEFAULT SYSDATE,
	updatedate DATE DEFAULT SYSDATE
)

SELECT * FROM MEMBER
